### ISSUE TITLE
Pydantic Error on attempting to import DirectConnector

### ISSUE THREAD

**Issue by HeyItsJono** [pglaum/pyjd#4]
`from pyjd.direct_connector import DirectConnector` (as in the example) leads to the following error:

```
>>> from pyjd.direct_connector import DirectConnector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Python\pyjd\.venv\Lib\site-packages\pyjd\direct_connector.py", line 1, in <module>
    from .jd_device import JDDevice
  File "Python\pyjd\.venv\Lib\site-packages\pyjd\jd_device.py", line 2, in <module>
    from .accounts import Accounts
  File "Python\pyjd\.venv\Lib\site-packages\pyjd\accounts.py", line 1, in <module>
    from .jd_types import Account, AccountQuery, BasicAuth, BasicAuthType
  File "Python\pyjd\.venv\Lib\site-packages\pyjd\jd_types.py", line 594, in <module>
    class IconDescriptor(BaseModel):
  File "Python\pyjd\.venv\Lib\site-packages\pydantic\main.py", line 286, in __new__
    cls.__try_update_forward_refs__()
  File "Python\pyjd\.venv\Lib\site-packages\pydantic\main.py", line 808, in __try_update_forward_refs__
    update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
  File "Python\pyjd\.venv\Lib\site-packages\pydantic\typing.py", line 554, in update_model_forward_refs
    update_field_forward_refs(f, globalns=globalns, localns=localns)
  File "Python\pyjd\.venv\Lib\site-packages\pydantic\typing.py", line 520, in update_field_forward_refs
    field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Python\pyjd\.venv\Lib\site-packages\pydantic\typing.py", line 66, in evaluate_forwardref
    return cast(Any, type_)._evaluate(globalns, localns, set())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
```

**Comment by pglaum** [comment]
That was apparently a pydantic bug with python 3.12.4+ & 3.13.

I will bump the pydantic dependency, then it should work.

**Comment by HeyItsJono** [comment]
Thank you for fixing that. Strangely, installing this new version via pip still gets pydantic 1.10.10, even though it's clearly fetching the new pyjd version:

```
pip install pyjd --no-cache-dir
Collecting pyjd
  Downloading pyjd-1.0.11-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: requests in d:\directory\.venv\lib\site-packages (from pyjd) (2.32.3)
Collecting pydantic==1.10.10 (from pyjd)
  Downloading pydantic-1.10.10-py3-none-any.whl.metadata (148 kB)
Collecting pycryptodome (from pyjd)
  Downloading pycryptodome-3.21.0-cp36-abi3-win_amd64.whl.metadata (3.4 kB)
Requirement already satisfied: typing-extensions>=4.2.0 in d:\directory\.venv\lib\site-packages (from pydantic==1.10.10->pyjd) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\directory\.venv\lib\site-packages (from requests->pyjd) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in d:\directory\.venv\lib\site-packages (from requests->pyjd) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\directory\.venv\lib\site-packages (from requests->pyjd) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in d:\directory\.venv\lib\site-packages (from requests->pyjd) (2024.8.30)
Downloading pyjd-1.0.11-py3-none-any.whl (35 kB)
Downloading pydantic-1.10.10-py3-none-any.whl (158 kB)
Downloading pycryptodome-3.21.0-cp36-abi3-win_amd64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 7.1 MB/s eta 0:00:00
Installing collected packages: pydantic, pycryptodome, pyjd
Successfully installed pycryptodome-3.21.0 pydantic-1.10.10 pyjd-1.0.11
```

I can over this by using `pip install --force-reinstall -v pydantic=1.10.19`, but it's odd pip seems to still think you want 1.10.10.
